select
    nullif(trim(operationId), '')          as operationId,
    nullif(trim(originalOperationId), '')  as originalOperationId,
    type,
    nullif(trim(processingEntity), '')     as processingEntity,
    nullif(trim(psp), '')                  as psp,
    nullif(trim(merchantAccount), '')      as merchantAccount,
    nullif(trim(purchaseId), '')           as purchaseId,
    grossCreditAmount,
    grossDebitAmount,
    transactionId,
    batchNumber,
    transactionAmount,
    transactionDate,
    reportCreationDate,
    originalFilename,
    reportRecordCount,
    currency,
    feeAmount,
    nullif(trim(feeCurrency), '')          as feeCurrency
from {{ ref('bronze_settlement') }}
